BookStoreWebUI/BookStoreWebUI/Controllers/BookController.cs
using BookStoreWebUI.Models.Books;
using BookStoreWebUI.Models.Common;
using BookStoreWebUI.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace BookStoreWebUI.Controllers
{
    public class BookController : BaseController
    {
        // GET: Book
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> GetBookList()
        {
            APIBaseFilterInfo filterInfo = CreateGridviewViewFilter(Request.Form, typeof(eBookGridview));
            BookListViewModel bookModel = await DataAccess.DataAccess.GetBookListAsync(filterInfo);

            GridviewJsonResponse jsonResponse = CreateGridviewJsonResponse(filterInfo.Draw, bookModel);

            return Json(jsonResponse);
        }

        [HttpGet]
        public async Task<ActionResult> Detail(int id)
        {
            BookViewModel bookModel = await DataAccess.DataAccess.GetBookAsync(id);

            return View("~/Views/Book/Detail.cshtml", bookModel.Book);
        }
    }
}

BookStoreWebUI/BookStoreWebUI/Controllers/CartController.cs
using BookStoreWebUI.Models.Cart;
using BookStoreWebUI.Models.Common;
using BookStoreWebUI.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace BookStoreWebUI.Controllers
{
    [Authorize]
    public class CartController : BaseController
    {
        [HttpPost]
        public async Task<ActionResult> AddCart(ReqCartUpdateInfo model)
        {
            ResCartUpdateInfo response = await DataAccess.DataAccess.UpdateCart(LoginUserInfo, model, eCartOption.Add);

            return Json(new JsonResponse() { Success = response.Result.Code == Constants.ACK_RESULT, Message = response.Result.Message });
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            ResGetCartInfo response = await DataAccess.DataAccess.GetCartInfo(LoginUserInfo);

            return View("~/Views/Cart/Index.cshtml", response.CartInfos);
        }

        [HttpPost]
        public async Task<ActionResult> CheckOut(ReqCheckOutInfo model)
        {
            ResCheckOut response = await DataAccess.DataAccess.CheckOut(LoginUserInfo, model);

            return Json(new JsonResponse() { Success = response.Result.Code == Constants.ACK_RESULT, Message =response.Result.Message });
        }
    }
}

BookStoreWebUI/BookStoreWebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/modernizr")*@
    @Scripts.Render("~/bundles/commonLibs")
    @Scripts.Render("~/bundles/operationLibs")
    <script>
        commonUtil.AppRootDir = "@HttpRuntime.AppDomainAppVirtualPath";

        if (commonUtil.AppRootDir === '/') {
            commonUtil.AppRootDir = '';
        }

        console.log(commonUtil.AppRootDir);
    </script>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="@Url.Action("Index", "Book")">Book Store</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse right" id="navbarNavDropdown">
                <ul class="navbar-nav ms-auto">
                    @*<li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="@Url.Action("Index", "Home")">Home</a>
                        </li>*@
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Cart")"><i class="fa fa-shopping-cart"></i></a>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item dropdown" style="justify-self: end;">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownAdminMGMT" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                @{
                                    BookStoreWebUI.Models.Account.LoginUserInfo obj = Session[BookStoreWebUI.Utils.Constants.SESSION_WEB_LOGIN_INFO] as BookStoreWebUI.Models.Account.LoginUserInfo;
                                    if (obj != null)
                                    {
                                        @obj.UserDlpName
                                    }
                                }
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownAdminMGMT">
                                <li><a class="dropdown-item" href="@Url.Action("Index", "Orders")">My Orders (Not Implemented)</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("ChangePassword", "User")">Change Password (Not Implemented)</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("Logout", "Account")">Logout</a></li>
                            </ul>
                        </li>
                    }

                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid body-content">
        @RenderBody()
    </div>

    <div id="DialogContainer"></div>

    <footer class="footer-bs">
        <div class="container-fluid">
            <hr />
            <div style="float:right">
                <label>&copy; @DateTime.Now.Year - Company Name</label>
            </div>

        </div>
    </footer>

    @*@Html.Partial("~/Views/Shared/_JSResourcesPartialView.cshtml")*@

    @RenderSection("scripts", required: false)
</body>
</html>